#!/usr/bin/env bash
set -eo pipefail

export ODOO_GEN_HOME=${ODOO_GEN_HOME:="$GENERATEDS_HOME/odoo"}

generate_file() {
  local schema_name=$1
  local version=$2
  local module_name=$3
  local file=$4
  local output_dir="$ROOT_DIR/l10n_br_spec_$schema_name/models/$version"

  if [[ ! -f "$ODOO_GEN_HOME"/gends_run_gen_odoo.py ]]; then
    echo ""
    echo "WARNING! You should download the Odoo generateds plugin in $ODOO_GEN_HOME"
    echo "If you have the plugin installed elsewhere, instead before running the script do:"
    echo "export ODOO_GEN_HOME=<your_generateds_odoo_plugin_folder>"
    echo ""
  fi
  # you can debug the XML preprocessing by commenting:
  # python "$GENERATEDS_HOME"/process_includes.py "$file" > /tmp/debug_$module_name.xml

  python "$ODOO_GEN_HOME"/gends_run_gen_odoo.py -f -p "$GENERATEDS_HOME/generateDS.py" -l "$schema_name" -x "$version" -d "$output_dir" -v $file
  #autopep8 --in-place -p3 models.py
  echo "from . import $module_name" >> "$output_dir"/__init__.py
}

generate_file $@
